# Generated by Django 3.1.4 on 2020-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GLN', models.CharField(max_length=80)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='GLN',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='price',
        ),
        migrations.AddField(
            model_name='pedido',
            name='articulos',
            field=models.ManyToManyField(to='pedido.Articulo'),
        ),
    ]
