# Generated by Django 3.1.4 on 2020-12-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20201218_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='articulos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.articulo'),
        ),
    ]
