# Generated by Django 3.1.4 on 2020-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20201218_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
    ]
