# Generated by Django 3.1.4 on 2020-12-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
    ]
