# Generated by Django 3.1.4 on 2020-12-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_remove_pedido_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default=1112223, max_length=20),
            preserve_default=False,
        ),
    ]
