# Generated by Django 3.1.4 on 2020-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20201219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
